using System;
using System.Collections.Generic;
using DataGraph.Editor.Domain;
using DataGraph.Runtime;

namespace DataGraph.Editor.CodeGen
{
    /// <summary>
    /// Generates Blob struct definitions and a typed BlobBuilder from a ParseableGraph.
    /// Produces three files per graph:
    /// - Entry structs ({GraphName}Blob.cs)
    /// - Database wrapper struct ({GraphName}BlobDatabase.cs)
    /// - Builder that constructs BlobAssetReference from raw data ({GraphName}BlobBuilder.cs)
    /// </summary>
    internal sealed class BlobCodeGenerator
    {
        /// <summary>
        /// Generates Blob entry struct definitions.
        /// </summary>
        public Result<string> GenerateEntries(ParseableGraph graph)
        {
            if (graph == null)
                return Result<string>.Failure("Graph is null.");

            try
            {
                var writer = new CodeWriter();
                WriteHeader(writer);
                writer.BeginBlock("namespace DataGraph.Data");
                WriteRootStruct(writer, graph.Root);
                writer.EndBlock();
                return Result<string>.Success(writer.ToString());
            }
            catch (Exception ex)
            {
                return Result<string>.Failure($"Blob code generation failed: {ex.Message}");
            }
        }

        /// <summary>
        /// Generates Blob database wrapper struct with lookup methods.
        /// </summary>
        public Result<string> GenerateDatabase(ParseableGraph graph)
        {
            if (graph == null)
                return Result<string>.Failure("Graph is null.");

            try
            {
                var writer = new CodeWriter();
                WriteHeader(writer);
                writer.BeginBlock("namespace DataGraph.Data");
                WriteDatabaseStruct(writer, graph.GraphName, graph.Root);
                writer.EndBlock();
                return Result<string>.Success(writer.ToString());
            }
            catch (Exception ex)
            {
                return Result<string>.Failure($"Blob code generation failed: {ex.Message}");
            }
        }

        /// <summary>
        /// Generates a typed builder class that constructs BlobAssetReference
        /// from parallel key/value arrays. Used by the serializer.
        /// </summary>
        public Result<string> GenerateBuilder(ParseableGraph graph)
        {
            if (graph == null)
                return Result<string>.Failure("Graph is null.");

            try
            {
                var writer = new CodeWriter();
                WriteBlobBuilderHeader(writer);
                writer.BeginBlock("namespace DataGraph.Data");
                WriteBlobBuilderClass(writer, graph.GraphName, graph.Root);
                writer.EndBlock();
                return Result<string>.Success(writer.ToString());
            }
            catch (Exception ex)
            {
                return Result<string>.Failure($"Blob builder generation failed: {ex.Message}");
            }
        }

        // ==================== HEADERS ====================

        private static void WriteHeader(CodeWriter w)
        {
            w.Line("// <auto-generated>");
            w.Line("// Generated by DataGraph. Do not modify.");
            w.Line("// </auto-generated>");
            w.BlankLine();
            w.Line("using Unity.Collections;");
            w.Line("using Unity.Entities;");
            w.BlankLine();
        }

        private static void WriteBlobBuilderHeader(CodeWriter w)
        {
            w.Line("// <auto-generated>");
            w.Line("// Generated by DataGraph. Do not modify.");
            w.Line("// </auto-generated>");
            w.BlankLine();
            w.Line("using System.Collections.Generic;");
            w.Line("using Unity.Collections;");
            w.Line("using Unity.Entities;");
            w.Line("using DataGraph.Data;");
            w.BlankLine();
        }

        // ==================== STRUCT GENERATION ====================

        private void WriteRootStruct(CodeWriter w, ParseableNode root)
        {
            WriteStruct(w, RootTypeResolver.GetTypeName(root), root.Children);
        }

        private void WriteStruct(CodeWriter w, string typeName, IReadOnlyList<ParseableNode> children)
        {
            var blobName = typeName + "Blob";
            w.BeginBlock($"public struct {blobName}");

            foreach (var child in children)
                WriteField(w, child);

            w.EndBlock();

            foreach (var child in children)
                WriteNestedStructs(w, child);
        }

        private void WriteField(CodeWriter w, ParseableNode node)
        {
            switch (node)
            {
                case ParseableCustomField custom:
                    w.Line($"public {TypeMapper.GetBlobType(custom.ValueType)} {custom.FieldName};");
                    break;

                case ParseableEnumField enumField:
                    w.Line($"public {enumField.EnumTypeName} {enumField.FieldName};");
                    break;

                case ParseableFlagField flagField:
                    w.Line($"public {flagField.FlagTypeName} {flagField.FieldName};");
                    break;

                case ParseableAssetField:
                    w.Line($"public BlobString {node.FieldName};");
                    break;

                case ParseableObjectField obj:
                    w.Line($"public {obj.TypeName}Blob {obj.FieldName};");
                    break;

                case ParseableArrayField arr:
                    w.Line($"public BlobArray<{GetArrayElementBlobType(arr)}> {arr.FieldName};");
                    break;

                case ParseableDictionaryField dict:
                    var keyBlobType = dict.KeyType == KeyType.String ? "BlobString" : "int";
                    var valueType = GetDictionaryValueBlobType(dict);
                    w.Line($"public BlobArray<{keyBlobType}> {dict.FieldName}Keys;");
                    w.Line($"public BlobArray<{valueType}> {dict.FieldName}Values;");
                    break;
            }
        }

        private void WriteNestedStructs(CodeWriter w, ParseableNode node)
        {
            switch (node)
            {
                case ParseableObjectField obj:
                    w.BlankLine();
                    WriteStruct(w, obj.TypeName, obj.Children);
                    break;

                case ParseableArrayField arr when arr.Mode == ArrayMode.Vertical && CodeGenHelpers.HasStructuralChildren(arr):
                    w.BlankLine();
                    WriteStruct(w, arr.TypeName, arr.Children);
                    break;

                case ParseableDictionaryField dict when CodeGenHelpers.HasStructuralChildren(dict):
                    w.BlankLine();
                    WriteStruct(w, dict.TypeName, dict.Children);
                    break;
            }
        }

        // ==================== DATABASE STRUCT ====================

        private void WriteDatabaseStruct(CodeWriter w, string graphName, ParseableNode root)
        {
            var dbName = $"{graphName}BlobDatabase";

            switch (root)
            {
                case ParseableDictionaryRoot dict:
                {
                    var entryBlob = dict.TypeName + "Blob";
                    var keyType = TypeMapper.GetKeyTypeName(dict.KeyType);
                    w.BeginBlock($"public struct {dbName}");
                    w.Line($"public BlobArray<{keyType}> keys;");
                    w.Line($"public BlobArray<{entryBlob}> values;");
                    w.BlankLine();
                    w.BeginBlock($"public ref {entryBlob} GetById({keyType} key)");
                    w.Line("int lo = 0, hi = keys.Length - 1;");
                    w.Line("while (lo <= hi)");
                    w.BeginBlock("");
                    w.Line("int mid = lo + (hi - lo) / 2;");
                    if (dict.KeyType == KeyType.Int)
                    {
                        w.Line("if (keys[mid] == key) return ref values[mid];");
                        w.Line("if (keys[mid] < key) lo = mid + 1;");
                    }
                    else
                    {
                        w.Line("int cmp = string.Compare(keys[mid].ToString(), key, System.StringComparison.Ordinal);");
                        w.Line("if (cmp == 0) return ref values[mid];");
                        w.Line("if (cmp < 0) lo = mid + 1;");
                    }
                    w.Line("else hi = mid - 1;");
                    w.EndBlock();
                    w.Line($"throw new System.Collections.Generic.KeyNotFoundException($\"No {entryBlob} with key '{{key}}'.\");");
                    w.EndBlock();
                    w.EndBlock();
                    break;
                }

                case ParseableArrayRoot arr:
                {
                    var entryBlob = arr.TypeName + "Blob";
                    w.BeginBlock($"public struct {dbName}");
                    w.Line($"public BlobArray<{entryBlob}> entries;");
                    w.BlankLine();
                    w.BeginBlock($"public ref {entryBlob} GetByIndex(int index)");
                    w.Line("return ref entries[index];");
                    w.EndBlock();
                    w.EndBlock();
                    break;
                }

                case ParseableObjectRoot obj:
                {
                    var entryBlob = obj.TypeName + "Blob";
                    w.BeginBlock($"public struct {dbName}");
                    w.Line($"public {entryBlob} data;");
                    w.EndBlock();
                    // No GetObject() instance method: C# forbids returning a
                    // ref to a struct field from an instance member (CS8170).
                    // Callers access the field directly via dbRef.Value.data
                    // or through the Register lambda below.
                    break;
                }
            }
        }

        // ==================== BUILDER CLASS ====================

        private void WriteBlobBuilderClass(CodeWriter w, string graphName, ParseableNode root)
        {
            var dbName = $"{graphName}BlobDatabase";
            var builderName = $"{graphName}BlobDatabaseBuilder";
            var entryBlob = GetRootEntryBlobName(root);

            w.BeginBlock($"public static class {builderName}");

            switch (root)
            {
                case ParseableDictionaryRoot dict:
                    WriteDictionaryBuilder(w, dbName, dict);
                    break;
                case ParseableArrayRoot arr:
                    WriteArrayBuilder(w, dbName, arr);
                    break;
                case ParseableObjectRoot obj:
                    WriteObjectBuilder(w, dbName, obj);
                    break;
            }

            w.BlankLine();
            WriteRegisterMethod(w, dbName, entryBlob, root);

            w.BlankLine();
            w.BeginBlock($"public static void Save(BlobAssetReference<{dbName}> blobRef, string path)");
            w.Line($"BlobFileUtility.Save(blobRef, path);");
            w.EndBlock();

            w.BlankLine();
            w.BeginBlock($"public static BlobAssetReference<{dbName}> Load(string path)");
            w.Line($"return BlobFileUtility.Load<{dbName}>(path);");
            w.EndBlock();

            w.EndBlock();
        }

        private static string GetRootEntryBlobName(ParseableNode root)
        {
            return root switch
            {
                ParseableDictionaryRoot dict => dict.TypeName + "Blob",
                ParseableArrayRoot arr => arr.TypeName + "Blob",
                ParseableObjectRoot obj => obj.TypeName + "Blob",
                _ => "Unknown"
            };
        }

        private void WriteRegisterMethod(CodeWriter w, string dbName, string entryBlob, ParseableNode root)
        {
            w.BeginBlock($"public static void Register(BlobAssetReference<{dbName}> blobRef)");

            switch (root)
            {
                case ParseableDictionaryRoot:
                    w.Line($"var handle = new BlobDatabaseHandle<{entryBlob}, {dbName}>(");
                    w.Line($"    blobRef,");
                    w.Line($"    getById: (ref {dbName} db, int key) => ref db.GetById(key));");
                    break;
                case ParseableArrayRoot:
                    w.Line($"var handle = new BlobDatabaseHandle<{entryBlob}, {dbName}>(");
                    w.Line($"    blobRef,");
                    w.Line($"    getByIndex: (ref {dbName} db, int index) => ref db.GetByIndex(index));");
                    break;
                case ParseableObjectRoot:
                    w.Line($"var handle = new BlobDatabaseHandle<{entryBlob}, {dbName}>(");
                    w.Line($"    blobRef,");
                    w.Line($"    getObject: (ref {dbName} db) => ref db.data);");
                    break;
            }

            w.Line($"BlobDatabase.Register<{entryBlob}, {dbName}>(blobRef, handle);");
            w.EndBlock();
        }

        private void WriteDictionaryBuilder(CodeWriter w, string dbName, ParseableDictionaryRoot root)
        {
            var entryBlob = root.TypeName + "Blob";
            var keyType = TypeMapper.GetKeyTypeName(root.KeyType);

            w.BeginBlock($"public static BlobAssetReference<{dbName}> Build({keyType}[] keys, {entryBlob}Source[] values)");
            w.Line("System.Array.Sort(keys, values);");
            w.Line("var builder = new BlobBuilder(Allocator.Temp);");
            w.Line($"ref var dbRoot = ref builder.ConstructRoot<{dbName}>();");
            w.BlankLine();
            w.Line("var keysBuilder = builder.Allocate(ref dbRoot.keys, keys.Length);");
            w.Line("for (int i = 0; i < keys.Length; i++)");
            w.Line("    keysBuilder[i] = keys[i];");
            w.BlankLine();
            w.Line("var valuesBuilder = builder.Allocate(ref dbRoot.values, values.Length);");
            w.Line("for (int i = 0; i < values.Length; i++)");
            w.BeginBlock("");
            WriteFieldAssignments(w, "valuesBuilder[i]", "values[i]", root.Children);
            w.EndBlock();
            w.BlankLine();
            w.Line($"var result = builder.CreateBlobAssetReference<{dbName}>(Allocator.Persistent);");
            w.Line("builder.Dispose();");
            w.Line("return result;");
            w.EndBlock();

            w.BlankLine();
            WriteSourceStruct(w, root.TypeName, root.Children);
        }

        private void WriteArrayBuilder(CodeWriter w, string dbName, ParseableArrayRoot root)
        {
            var entryBlob = root.TypeName + "Blob";

            w.BeginBlock($"public static BlobAssetReference<{dbName}> Build({entryBlob}Source[] values)");
            w.Line("var builder = new BlobBuilder(Allocator.Temp);");
            w.Line($"ref var dbRoot = ref builder.ConstructRoot<{dbName}>();");
            w.BlankLine();
            w.Line($"var arrayBuilder = builder.Allocate(ref dbRoot.entries, values.Length);");
            w.Line("for (int i = 0; i < values.Length; i++)");
            w.BeginBlock("");
            WriteFieldAssignments(w, "arrayBuilder[i]", "values[i]", root.Children);
            w.EndBlock();
            w.BlankLine();
            w.Line($"var result = builder.CreateBlobAssetReference<{dbName}>(Allocator.Persistent);");
            w.Line("builder.Dispose();");
            w.Line("return result;");
            w.EndBlock();

            w.BlankLine();
            WriteSourceStruct(w, root.TypeName, root.Children);
        }

        private void WriteObjectBuilder(CodeWriter w, string dbName, ParseableObjectRoot root)
        {
            var entryBlob = root.TypeName + "Blob";

            w.BeginBlock($"public static BlobAssetReference<{dbName}> Build({entryBlob}Source source)");
            w.Line("var builder = new BlobBuilder(Allocator.Temp);");
            w.Line($"ref var dbRoot = ref builder.ConstructRoot<{dbName}>();");
            w.BlankLine();
            WriteFieldAssignments(w, "dbRoot.data", "source", root.Children);
            w.BlankLine();
            w.Line($"var result = builder.CreateBlobAssetReference<{dbName}>(Allocator.Persistent);");
            w.Line("builder.Dispose();");
            w.Line("return result;");
            w.EndBlock();

            w.BlankLine();
            WriteSourceStruct(w, root.TypeName, root.Children);
        }

        /// <summary>
        /// Generates a managed Source struct that mirrors the Blob struct
        /// but uses string instead of BlobString and List instead of BlobArray.
        /// Used as input to the Build method.
        /// </summary>
        private void WriteSourceStruct(CodeWriter w, string typeName, IReadOnlyList<ParseableNode> children)
        {
            var sourceName = typeName + "BlobSource";
            w.BeginBlock($"public struct {sourceName}");

            foreach (var child in children)
            {
                switch (child)
                {
                    case ParseableCustomField custom:
                        if (custom.ValueType == FieldValueType.String)
                            w.Line($"public string {custom.FieldName};");
                        else
                            w.Line($"public {TypeMapper.GetBlobType(custom.ValueType)} {custom.FieldName};");
                        break;

                    case ParseableEnumField enumField:
                        w.Line($"public {enumField.EnumTypeName} {enumField.FieldName};");
                        break;

                    case ParseableFlagField flagField:
                        w.Line($"public {flagField.FlagTypeName} {flagField.FieldName};");
                        break;

                    case ParseableAssetField:
                        w.Line($"public string {child.FieldName};");
                        break;

                    case ParseableObjectField obj:
                        w.Line($"public {obj.TypeName}BlobSource {obj.FieldName};");
                        break;

                    case ParseableArrayField arr:
                        var elementType = GetArrayElementSourceType(arr);
                        w.Line($"public {elementType}[] {arr.FieldName};");
                        break;

                    case ParseableDictionaryField dict:
                        var keyType = TypeMapper.GetKeyTypeName(dict.KeyType);
                        var valueType = GetDictionaryValueSourceType(dict);
                        w.Line($"public {keyType}[] {dict.FieldName}Keys;");
                        w.Line($"public {valueType}[] {dict.FieldName}Values;");
                        break;
                }
            }

            w.EndBlock();

            foreach (var child in children)
            {
                switch (child)
                {
                    case ParseableObjectField obj:
                        w.BlankLine();
                        WriteSourceStruct(w, obj.TypeName, obj.Children);
                        break;
                    case ParseableArrayField arr when arr.Mode == ArrayMode.Vertical && CodeGenHelpers.HasStructuralChildren(arr):
                        w.BlankLine();
                        WriteSourceStruct(w, arr.TypeName, arr.Children);
                        break;
                    case ParseableDictionaryField dict when CodeGenHelpers.HasStructuralChildren(dict):
                        w.BlankLine();
                        WriteSourceStruct(w, dict.TypeName, dict.Children);
                        break;
                }
            }
        }

        private void WriteFieldAssignments(CodeWriter w, string target, string source,
            IReadOnlyList<ParseableNode> children)
        {
            foreach (var child in children)
            {
                switch (child)
                {
                    case ParseableCustomField custom when custom.ValueType == FieldValueType.String:
                        w.Line($"builder.AllocateString(ref {target}.{custom.FieldName}, {source}.{custom.FieldName} ?? \"\");");
                        break;

                    case ParseableCustomField custom:
                        w.Line($"{target}.{custom.FieldName} = {source}.{custom.FieldName};");
                        break;

                    case ParseableEnumField enumField:
                        w.Line($"{target}.{enumField.FieldName} = {source}.{enumField.FieldName};");
                        break;

                    case ParseableFlagField flagField:
                        w.Line($"{target}.{flagField.FieldName} = {source}.{flagField.FieldName};");
                        break;

                    case ParseableAssetField:
                        w.Line($"builder.AllocateString(ref {target}.{child.FieldName}, {source}.{child.FieldName} ?? \"\");");
                        break;

                    case ParseableObjectField obj:
                        WriteFieldAssignments(w, $"{target}.{obj.FieldName}", $"{source}.{obj.FieldName}", obj.Children);
                        break;

                    case ParseableArrayField arr:
                        WriteArrayAssignment(w, target, source, arr);
                        break;

                    case ParseableDictionaryField dict:
                        WriteDictionaryAssignment(w, target, source, dict);
                        break;
                }
            }
        }

        private void WriteArrayAssignment(CodeWriter w, string target, string source, ParseableArrayField arr)
        {
            var fieldName = arr.FieldName;
            var iterVar = $"_i_{fieldName}";
            var elementBlobType = GetArrayElementBlobType(arr);

            w.Line($"if ({source}.{fieldName} != null && {source}.{fieldName}.Length > 0)");
            w.BeginBlock("");
            w.Line($"var _{fieldName}Builder = builder.Allocate(ref {target}.{fieldName}, {source}.{fieldName}.Length);");
            w.Line($"for (int {iterVar} = 0; {iterVar} < {source}.{fieldName}.Length; {iterVar}++)");
            w.BeginBlock("");

            if (string.IsNullOrEmpty(arr.TypeName) && arr.Children.Count == 1 && arr.Children[0] is ParseableCustomField leaf)
            {
                if (leaf.ValueType == FieldValueType.String)
                    w.Line($"builder.AllocateString(ref _{fieldName}Builder[{iterVar}], {source}.{fieldName}[{iterVar}] ?? \"\");");
                else
                    w.Line($"_{fieldName}Builder[{iterVar}] = {source}.{fieldName}[{iterVar}];");
            }
            else
            {
                WriteFieldAssignments(w, $"_{fieldName}Builder[{iterVar}]", $"{source}.{fieldName}[{iterVar}]", arr.Children);
            }

            w.EndBlock();
            w.EndBlock();
        }

        private void WriteDictionaryAssignment(CodeWriter w, string target, string source, ParseableDictionaryField dict)
        {
            var fieldName = dict.FieldName;
            var iterVar = $"_i_{fieldName}";

            w.Line($"if ({source}.{fieldName}Keys != null && {source}.{fieldName}Keys.Length > 0)");
            w.BeginBlock("");
            w.Line($"var _{fieldName}KeysBuilder = builder.Allocate(ref {target}.{fieldName}Keys, {source}.{fieldName}Keys.Length);");
            w.Line($"for (int {iterVar} = 0; {iterVar} < {source}.{fieldName}Keys.Length; {iterVar}++)");
            w.Line($"    _{fieldName}KeysBuilder[{iterVar}] = {source}.{fieldName}Keys[{iterVar}];");
            w.BlankLine();
            w.Line($"var _{fieldName}ValsBuilder = builder.Allocate(ref {target}.{fieldName}Values, {source}.{fieldName}Values.Length);");
            w.Line($"for (int {iterVar}v = 0; {iterVar}v < {source}.{fieldName}Values.Length; {iterVar}v++)");
            w.BeginBlock("");

            if (string.IsNullOrEmpty(dict.TypeName) && dict.Children.Count == 1 && dict.Children[0] is ParseableCustomField leaf)
            {
                if (leaf.ValueType == FieldValueType.String)
                    w.Line($"builder.AllocateString(ref _{fieldName}ValsBuilder[{iterVar}v], {source}.{fieldName}Values[{iterVar}v] ?? \"\");");
                else
                    w.Line($"_{fieldName}ValsBuilder[{iterVar}v] = {source}.{fieldName}Values[{iterVar}v];");
            }
            else
            {
                WriteFieldAssignments(w, $"_{fieldName}ValsBuilder[{iterVar}v]", $"{source}.{fieldName}Values[{iterVar}v]", dict.Children);
            }

            w.EndBlock();
            w.EndBlock();
        }

        private string GetArrayElementBlobType(ParseableArrayField arr)
        {
            if (arr.Mode == ArrayMode.Horizontal)
            {
                if (arr.Children.Count > 0 && arr.Children[0] is ParseableCustomField leaf)
                    return TypeMapper.GetBlobType(leaf.ValueType);
                return "BlobString";
            }

            if (string.IsNullOrEmpty(arr.TypeName) && arr.Children.Count == 1 && arr.Children[0] is ParseableCustomField singleLeaf)
                return TypeMapper.GetBlobType(singleLeaf.ValueType);

            return arr.TypeName + "Blob";
        }

        private string GetArrayElementSourceType(ParseableArrayField arr)
        {
            if (arr.Mode == ArrayMode.Horizontal)
            {
                if (arr.Children.Count > 0 && arr.Children[0] is ParseableCustomField leaf)
                    return leaf.ValueType == FieldValueType.String ? "string" : TypeMapper.GetBlobType(leaf.ValueType);
                return "string";
            }

            if (string.IsNullOrEmpty(arr.TypeName) && arr.Children.Count == 1 && arr.Children[0] is ParseableCustomField singleLeaf)
                return singleLeaf.ValueType == FieldValueType.String ? "string" : TypeMapper.GetBlobType(singleLeaf.ValueType);

            return arr.TypeName + "BlobSource";
        }

        private string GetDictionaryValueBlobType(ParseableDictionaryField dict)
        {
            if (string.IsNullOrEmpty(dict.TypeName) && dict.Children.Count == 1 && dict.Children[0] is ParseableCustomField singleLeaf)
                return TypeMapper.GetBlobType(singleLeaf.ValueType);

            return dict.TypeName + "Blob";
        }

        private string GetDictionaryValueSourceType(ParseableDictionaryField dict)
        {
            if (string.IsNullOrEmpty(dict.TypeName) && dict.Children.Count == 1 && dict.Children[0] is ParseableCustomField singleLeaf)
                return singleLeaf.ValueType == FieldValueType.String ? "string" : TypeMapper.GetBlobType(singleLeaf.ValueType);

            return dict.TypeName + "BlobSource";
        }

    }
}
