using System;
using System.Collections.Generic;
using DataGraph.Editor.Domain;
using DataGraph.Runtime;

namespace DataGraph.Editor.CodeGen
{
    /// <summary>
    /// Generates type-safe C# source code from a ParseableGraph definition.
    /// Dictionary fields are stored as parallel key/value lists (Unity serializable)
    /// with a runtime property that reconstructs the Dictionary on first access.
    /// </summary>
    internal sealed class CodeGenerator
    {
        public Result<string> GenerateEntries(ParseableGraph graph)
        {
            if (graph == null)
                return Result<string>.Failure("Graph is null.");

            try
            {
                var writer = new CodeWriter();
                WriteHeader(writer);
                writer.BeginBlock("namespace DataGraph.Data");
                WriteRootClass(writer, graph.Root);
                writer.EndBlock();
                return Result<string>.Success(writer.ToString());
            }
            catch (Exception ex)
            {
                return Result<string>.Failure($"Code generation failed: {ex.Message}");
            }
        }

        public Result<string> GenerateDatabase(ParseableGraph graph)
        {
            if (graph == null)
                return Result<string>.Failure("Graph is null.");

            try
            {
                var writer = new CodeWriter();
                WriteHeader(writer);
                writer.BeginBlock("namespace DataGraph.Data");
                WriteDatabaseClass(writer, graph.GraphName, graph.Root);
                writer.EndBlock();
                return Result<string>.Success(writer.ToString());
            }
            catch (Exception ex)
            {
                return Result<string>.Failure($"Code generation failed: {ex.Message}");
            }
        }

        public Result<string> GenerateEnum(ParsedEnumDefinition enumDef)
        {
            if (enumDef == null)
                return Result<string>.Failure("Enum definition is null.");

            if (enumDef.Members.Count == 0)
                return Result<string>.Failure(
                    $"Enum '{enumDef.TypeName}' has no members.");

            try
            {
                var writer = new CodeWriter();
                writer.Line("// <auto-generated>");
                writer.Line("// Generated by DataGraph. Do not modify.");
                writer.Line("// </auto-generated>");
                writer.BlankLine();
                writer.BeginBlock("namespace DataGraph.Data");
                if (enumDef.IsFlags) writer.Line("[System.Flags]");
                writer.BeginBlock($"public enum {enumDef.TypeName}");
                for (int i = 0; i < enumDef.Members.Count; i++)
                {
                    var m = enumDef.Members[i];
                    writer.Line($"{m.Name} = {m.Value}{(i < enumDef.Members.Count - 1 ? "," : "")}");
                }
                writer.EndBlock();
                writer.EndBlock();
                return Result<string>.Success(writer.ToString());
            }
            catch (Exception ex)
            {
                return Result<string>.Failure($"Enum code generation failed: {ex.Message}");
            }
        }

        private void WriteHeader(CodeWriter w)
        {
            w.Line("// <auto-generated>");
            w.Line("// Generated by DataGraph. Do not modify.");
            w.Line("// </auto-generated>");
            w.BlankLine();
            w.Line("using System;");
            w.Line("using System.Collections.Generic;");
            w.Line("using UnityEngine;");
            w.Line("using DataGraph.Data;");
            w.BlankLine();
        }

        private void WriteRootClass(CodeWriter w, ParseableNode root)
        {
            switch (root)
            {
                case ParseableDictionaryRoot dict:
                    WriteClass(w, dict.TypeName, true, dict.Children);
                    break;
                case ParseableArrayRoot arr:
                    WriteClass(w, arr.TypeName, true, arr.Children);
                    break;
                case ParseableObjectRoot obj:
                    WriteClass(w, obj.TypeName, true, obj.Children);
                    break;
                case ParseableEnumRoot:
                case ParseableFlagRoot:
                    break;
            }
        }

        private void WriteClass(CodeWriter w, string typeName, bool isRoot,
            IReadOnlyList<ParseableNode> children)
        {
            var dictFields = CollectDictionaryFields(children);

            w.Line("[Serializable]");
            w.BeginBlock(isRoot
                ? $"public class {typeName} : DataGraphEntry"
                : $"public class {typeName}");

            foreach (var child in children)
            {
                if (child is ParseableDictionaryField dict)
                    WriteDictionaryFieldAsLists(w, dict);
                else
                    WriteField(w, child);
            }

            w.EndBlock();

            foreach (var child in children)
                WriteNestedClasses(w, child);
        }

        private void WriteField(CodeWriter w, ParseableNode node)
        {
            switch (node)
            {
                case ParseableCustomField custom:
                    w.Line($"public {TypeMapper.GetCSharpTypeName(custom.ValueType, custom.EnumType)} {custom.FieldName};");
                    break;
                case ParseableAssetField asset:
                    w.Line($"public {AssetTypeMapper.GetCSharpTypeName(asset.AssetType)} {asset.FieldName};");
                    break;
                case ParseableEnumField enumField:
                    w.Line($"public {enumField.EnumTypeName} {enumField.FieldName};");
                    break;
                case ParseableFlagField flagField:
                    w.Line($"public {flagField.FlagTypeName} {flagField.FieldName};");
                    break;
                case ParseableObjectField obj:
                    w.Line($"public {obj.TypeName} {obj.FieldName};");
                    break;
                case ParseableArrayField arr:
                    w.Line($"public List<{GetArrayElementTypeName(arr)}> {arr.FieldName};");
                    break;
            }
        }

        /// <summary>
        /// Writes Dictionary field as two serialized lists + a runtime Dictionary property.
        /// Unity cannot serialize Dictionary directly, so we store parallel lists
        /// and reconstruct on access.
        /// </summary>
        private void WriteDictionaryFieldAsLists(CodeWriter w, ParseableDictionaryField dict)
        {
            var keyType = TypeMapper.GetKeyTypeName(dict.KeyType);
            var valueType = GetDictionaryValueTypeName(dict);
            var fn = dict.FieldName;

            w.Line($"public List<{keyType}> {fn}Keys = new();");
            w.Line($"public List<{valueType}> {fn}Values = new();");
            w.BlankLine();

            w.Line("[NonSerialized]");
            w.Line($"private Dictionary<{keyType}, {valueType}> _{fn}Cache;");

            w.BeginBlock($"public Dictionary<{keyType}, {valueType}> {fn}");
            w.BeginBlock("get");
            w.BeginBlock($"if (_{fn}Cache == null)");
            w.Line($"_{fn}Cache = new Dictionary<{keyType}, {valueType}>();");
            w.Line($"var count = Mathf.Min({fn}Keys.Count, {fn}Values.Count);");
            w.Line($"for (int i = 0; i < count; i++)");
            w.Line($"    _{fn}Cache[{fn}Keys[i]] = {fn}Values[i];");
            w.EndBlock();
            w.Line($"return _{fn}Cache;");
            w.EndBlock();
            w.EndBlock();
        }

        private void WriteNestedClasses(CodeWriter w, ParseableNode node)
        {
            switch (node)
            {
                case ParseableObjectField obj:
                    w.BlankLine();
                    WriteClass(w, obj.TypeName, false, obj.Children);
                    break;
                case ParseableArrayField arr
                    when arr.Mode == ArrayMode.Vertical && HasStructuralChildren(arr):
                    w.BlankLine();
                    WriteClass(w, arr.TypeName, false, arr.Children);
                    break;
                case ParseableDictionaryField dict when HasStructuralChildren(dict):
                    w.BlankLine();
                    WriteClass(w, dict.TypeName, false, dict.Children);
                    break;
            }
        }

        // ==================== HELPERS ====================

        private struct DictFieldInfo
        {
            public string FieldName;
            public string KeyTypeName;
            public string ValueTypeName;
        }

        private List<DictFieldInfo> CollectDictionaryFields(
            IReadOnlyList<ParseableNode> children)
        {
            var result = new List<DictFieldInfo>();
            foreach (var child in children)
                if (child is ParseableDictionaryField dict)
                    result.Add(new DictFieldInfo
                    {
                        FieldName = dict.FieldName,
                        KeyTypeName = TypeMapper.GetKeyTypeName(dict.KeyType),
                        ValueTypeName = GetDictionaryValueTypeName(dict)
                    });
            return result;
        }

        private string GetArrayElementTypeName(ParseableArrayField arr)
        {
            if (arr.Mode == ArrayMode.Horizontal)
            {
                if (arr.Children.Count > 0 && arr.Children[0] is ParseableCustomField leaf)
                    return TypeMapper.GetCSharpTypeName(leaf.ValueType, leaf.EnumType);
                return "object";
            }

            if (string.IsNullOrEmpty(arr.TypeName)
                && arr.Children.Count == 1
                && arr.Children[0] is ParseableCustomField singleLeaf)
                return TypeMapper.GetCSharpTypeName(singleLeaf.ValueType, singleLeaf.EnumType);

            return arr.TypeName;
        }

        private string GetDictionaryValueTypeName(ParseableDictionaryField dict)
        {
            if (string.IsNullOrEmpty(dict.TypeName)
                && dict.Children.Count == 1
                && dict.Children[0] is ParseableCustomField singleLeaf)
                return TypeMapper.GetCSharpTypeName(singleLeaf.ValueType, singleLeaf.EnumType);

            return dict.TypeName;
        }

        private static bool HasStructuralChildren(ParseableNode node)
        {
            var typeName = node switch
            {
                ParseableArrayField arr => arr.TypeName,
                ParseableDictionaryField dict => dict.TypeName,
                _ => null
            };
            if (!string.IsNullOrEmpty(typeName)) return node.Children.Count > 0;
            if (node.Children.Count == 1 && node.Children[0] is ParseableCustomField)
                return false;
            return node.Children.Count > 0;
        }

        private void WriteDatabaseClass(CodeWriter w, string graphName, ParseableNode root)
        {
            var dbClassName = $"{graphName}Database";
            switch (root)
            {
                case ParseableDictionaryRoot dict:
                    w.BeginBlock(
                        $"public class {dbClassName} : DictionaryDatabaseAsset<{TypeMapper.GetKeyTypeName(dict.KeyType)}, {dict.TypeName}>");
                    w.EndBlock();
                    break;
                case ParseableArrayRoot arr:
                    w.BeginBlock($"public class {dbClassName} : ArrayDatabaseAsset<{arr.TypeName}>");
                    w.EndBlock();
                    break;
                case ParseableObjectRoot obj:
                    w.BeginBlock($"public class {dbClassName} : ObjectDatabaseAsset<{obj.TypeName}>");
                    w.EndBlock();
                    break;
            }
        }
    }
}
