using System;
using System.Collections.Generic;
using DataGraph.Editor.Domain;
using DataGraph.Runtime;

namespace DataGraph.Editor.CodeGen
{
    /// <summary>
    /// Generates type-safe C# source code from a ParseableGraph definition.
    /// Produces one file per graph containing the root class and all
    /// nested classes. Generated code is standalone — no DataGraph
    /// runtime dependency beyond Database base classes.
    /// </summary>
    internal sealed class CodeGenerator
    {
        private readonly string _suffix;

        /// <summary>
        /// Creates a generator with the given class name suffix (e.g. "SO" for V1).
        /// </summary>
        public CodeGenerator(string suffix = "SO")
        {
            _suffix = suffix;
        }

        /// <summary>
        /// Generates C# source code for the given graph.
        /// Returns the complete file content as a string.
        /// </summary>
        public Result<string> Generate(ParseableGraph graph)
        {
            if (graph == null)
                return Result<string>.Failure("Graph is null.");

            try
            {
                var writer = new CodeWriter();
                WriteHeader(writer);
                WriteRootClass(writer, graph.Root);
                return Result<string>.Success(writer.ToString());
            }
            catch (Exception ex)
            {
                return Result<string>.Failure($"Code generation failed: {ex.Message}");
            }
        }

        private void WriteHeader(CodeWriter w)
        {
            w.Line("// <auto-generated>");
            w.Line("// Generated by DataGraph. Do not modify.");
            w.Line("// </auto-generated>");
            w.BlankLine();
            w.Line("using System;");
            w.Line("using System.Collections.Generic;");
            w.Line("using UnityEngine;");
            w.BlankLine();
        }

        private void WriteRootClass(CodeWriter w, ParseableNode root)
        {
            switch (root)
            {
                case ParseableDictionaryRoot dict:
                    WriteClass(w, dict.TypeName, true, dict.Children);
                    break;
                case ParseableArrayRoot arr:
                    WriteClass(w, arr.TypeName, true, arr.Children);
                    break;
                case ParseableObjectRoot obj:
                    WriteClass(w, obj.TypeName, true, obj.Children);
                    break;
                default:
                    throw new InvalidOperationException(
                        $"Unknown root type: {root.GetType().Name}");
            }
        }

        private void WriteClass(
            CodeWriter w,
            string typeName,
            bool isRoot,
            IReadOnlyList<ParseableNode> children)
        {
            var className = typeName + _suffix;

            if (isRoot)
            {
                w.BeginBlock($"public class {className} : ScriptableObject");
            }
            else
            {
                w.Line("[Serializable]");
                w.BeginBlock($"public class {className}");
            }

            foreach (var child in children)
            {
                WriteField(w, child);
            }

            w.EndBlock();

            foreach (var child in children)
            {
                WriteNestedClasses(w, child);
            }
        }

        private void WriteField(CodeWriter w, ParseableNode node)
        {
            switch (node)
            {
                case ParseableCustomField custom:
                    var csharpType = TypeMapper.GetCSharpTypeName(custom.ValueType, custom.EnumType);
                    w.Line($"public {csharpType} {custom.FieldName};");
                    break;

                case ParseableAssetField asset:
                    w.Line($"public {asset.AssetTypeName} {asset.FieldName};");
                    break;

                case ParseableObjectField obj:
                    w.Line($"public {obj.TypeName}{_suffix} {obj.FieldName};");
                    break;

                case ParseableArrayField arr:
                    var elementType = GetArrayElementTypeName(arr);
                    w.Line($"public List<{elementType}> {arr.FieldName};");
                    break;

                case ParseableDictionaryField dict:
                    var keyType = TypeMapper.GetKeyTypeName(dict.KeyType);
                    var valueType = GetDictionaryValueTypeName(dict);
                    w.Line($"public Dictionary<{keyType}, {valueType}> {dict.FieldName};");
                    break;
            }
        }

        private void WriteNestedClasses(CodeWriter w, ParseableNode node)
        {
            switch (node)
            {
                case ParseableObjectField obj:
                    w.BlankLine();
                    WriteClass(w, obj.TypeName, false, obj.Children);
                    break;

                case ParseableArrayField arr when arr.Mode == ArrayMode.Vertical && HasStructuralChildren(arr):
                    w.BlankLine();
                    WriteClass(w, arr.TypeName, false, arr.Children);
                    break;

                case ParseableDictionaryField dict when HasStructuralChildren(dict):
                    w.BlankLine();
                    WriteClass(w, dict.TypeName, false, dict.Children);
                    break;
            }
        }

        private string GetArrayElementTypeName(ParseableArrayField arr)
        {
            if (arr.Mode == ArrayMode.Horizontal)
            {
                if (arr.Children.Count > 0 && arr.Children[0] is ParseableCustomField leaf)
                    return TypeMapper.GetCSharpTypeName(leaf.ValueType, leaf.EnumType);
                return "object";
            }

            if (arr.Children.Count == 1 && arr.Children[0] is ParseableCustomField singleLeaf)
                return TypeMapper.GetCSharpTypeName(singleLeaf.ValueType, singleLeaf.EnumType);

            return arr.TypeName + _suffix;
        }

        private string GetDictionaryValueTypeName(ParseableDictionaryField dict)
        {
            if (dict.Children.Count == 1 && dict.Children[0] is ParseableCustomField singleLeaf)
                return TypeMapper.GetCSharpTypeName(singleLeaf.ValueType, singleLeaf.EnumType);

            return dict.TypeName + _suffix;
        }

        private static bool HasStructuralChildren(ParseableNode node)
        {
            if (node.Children.Count == 1 && node.Children[0] is ParseableCustomField)
                return false;
            return node.Children.Count > 0;
        }
    }
}
