using System;
using System.Collections.Generic;
using DataGraph.Editor.Domain;
using DataGraph.Runtime;

namespace DataGraph.Editor.CodeGen
{
    /// <summary>
    /// Generates type-safe C# source code from a ParseableGraph definition.
    /// For Data graphs: produces entry classes and database SO classes.
    /// For Enum/Flag graphs: produces C# enum definitions.
    /// </summary>
    internal sealed class CodeGenerator
    {
        /// <summary>
        /// Generates C# source for entry classes (e.g. Item, Reward).
        /// </summary>
        public Result<string> GenerateEntries(ParseableGraph graph)
        {
            if (graph == null)
                return Result<string>.Failure("Graph is null.");

            try
            {
                var writer = new CodeWriter();
                WriteHeader(writer);
                writer.BeginBlock("namespace DataGraph.Data");
                WriteRootClass(writer, graph.Root);
                writer.EndBlock();
                return Result<string>.Success(writer.ToString());
            }
            catch (Exception ex)
            {
                return Result<string>.Failure($"Code generation failed: {ex.Message}");
            }
        }

        /// <summary>
        /// Generates C# source for the database SO class (e.g. ItemsDatabase).
        /// </summary>
        public Result<string> GenerateDatabase(ParseableGraph graph)
        {
            if (graph == null)
                return Result<string>.Failure("Graph is null.");

            try
            {
                var writer = new CodeWriter();
                WriteHeader(writer);
                writer.BeginBlock("namespace DataGraph.Data");
                WriteDatabaseClass(writer, graph.GraphName, graph.Root);
                writer.EndBlock();
                return Result<string>.Success(writer.ToString());
            }
            catch (Exception ex)
            {
                return Result<string>.Failure($"Code generation failed: {ex.Message}");
            }
        }

        /// <summary>
        /// Generates C# enum source from a ParsedEnumDefinition.
        /// Used for EnumRoot and FlagRoot graphs.
        /// </summary>
        public Result<string> GenerateEnum(ParsedEnumDefinition enumDef)
        {
            if (enumDef == null)
                return Result<string>.Failure("Enum definition is null.");

            if (enumDef.Members.Count == 0)
                return Result<string>.Failure(
                    $"Enum '{enumDef.TypeName}' has no members.");

            try
            {
                var writer = new CodeWriter();
                writer.Line("// <auto-generated>");
                writer.Line("// Generated by DataGraph. Do not modify.");
                writer.Line("// </auto-generated>");
                writer.BlankLine();

                writer.BeginBlock("namespace DataGraph.Data");

                if (enumDef.IsFlags)
                    writer.Line("[System.Flags]");

                writer.BeginBlock($"public enum {enumDef.TypeName}");

                for (int i = 0; i < enumDef.Members.Count; i++)
                {
                    var member = enumDef.Members[i];
                    var comma = i < enumDef.Members.Count - 1 ? "," : "";
                    writer.Line($"{member.Name} = {member.Value}{comma}");
                }

                writer.EndBlock();
                writer.EndBlock();

                return Result<string>.Success(writer.ToString());
            }
            catch (Exception ex)
            {
                return Result<string>.Failure(
                    $"Enum code generation failed: {ex.Message}");
            }
        }

        private void WriteHeader(CodeWriter w)
        {
            w.Line("// <auto-generated>");
            w.Line("// Generated by DataGraph. Do not modify.");
            w.Line("// </auto-generated>");
            w.BlankLine();
            w.Line("using System;");
            w.Line("using System.Collections.Generic;");
            w.Line("using UnityEngine;");
            w.Line("using DataGraph.Data;");
            w.BlankLine();
        }

        private void WriteRootClass(CodeWriter w, ParseableNode root)
        {
            switch (root)
            {
                case ParseableDictionaryRoot dict:
                    WriteClass(w, dict.TypeName, true, dict.Children);
                    break;
                case ParseableArrayRoot arr:
                    WriteClass(w, arr.TypeName, true, arr.Children);
                    break;
                case ParseableObjectRoot obj:
                    WriteClass(w, obj.TypeName, true, obj.Children);
                    break;
                case ParseableEnumRoot:
                case ParseableFlagRoot:
                    break;
                default:
                    throw new InvalidOperationException(
                        $"Unknown root type: {root.GetType().Name}");
            }
        }

        private void WriteClass(
            CodeWriter w,
            string typeName,
            bool isRoot,
            IReadOnlyList<ParseableNode> children)
        {
            w.Line("[Serializable]");
            if (isRoot)
                w.BeginBlock($"public class {typeName} : DataGraphEntry");
            else
                w.BeginBlock($"public class {typeName}");

            foreach (var child in children)
                WriteField(w, child);

            w.EndBlock();

            foreach (var child in children)
                WriteNestedClasses(w, child);
        }

        private void WriteField(CodeWriter w, ParseableNode node)
        {
            switch (node)
            {
                case ParseableCustomField custom:
                    var csharpType = TypeMapper.GetCSharpTypeName(custom.ValueType, custom.EnumType);
                    w.Line($"public {csharpType} {custom.FieldName};");
                    break;

                case ParseableAssetField asset:
                    w.Line($"public {AssetTypeMapper.GetCSharpTypeName(asset.AssetType)} {asset.FieldName};");
                    break;

                case ParseableEnumField enumField:
                    w.Line($"public {enumField.EnumTypeName} {enumField.FieldName};");
                    break;

                case ParseableFlagField flagField:
                    w.Line($"public {flagField.FlagTypeName} {flagField.FieldName};");
                    break;

                case ParseableObjectField obj:
                    w.Line($"public {obj.TypeName} {obj.FieldName};");
                    break;

                case ParseableArrayField arr:
                    var elementType = GetArrayElementTypeName(arr);
                    w.Line($"public List<{elementType}> {arr.FieldName};");
                    break;

                case ParseableDictionaryField dict:
                    var keyType = TypeMapper.GetKeyTypeName(dict.KeyType);
                    var valueType = GetDictionaryValueTypeName(dict);
                    w.Line($"public Dictionary<{keyType}, {valueType}> {dict.FieldName};");
                    break;
            }
        }

        private void WriteNestedClasses(CodeWriter w, ParseableNode node)
        {
            switch (node)
            {
                case ParseableObjectField obj:
                    w.BlankLine();
                    WriteClass(w, obj.TypeName, false, obj.Children);
                    break;

                case ParseableArrayField arr when arr.Mode == ArrayMode.Vertical && HasStructuralChildren(arr):
                    w.BlankLine();
                    WriteClass(w, arr.TypeName, false, arr.Children);
                    break;

                case ParseableDictionaryField dict when HasStructuralChildren(dict):
                    w.BlankLine();
                    WriteClass(w, dict.TypeName, false, dict.Children);
                    break;
            }
        }

        private string GetArrayElementTypeName(ParseableArrayField arr)
        {
            if (arr.Mode == ArrayMode.Horizontal)
            {
                if (arr.Children.Count > 0 && arr.Children[0] is ParseableCustomField leaf)
                    return TypeMapper.GetCSharpTypeName(leaf.ValueType, leaf.EnumType);
                return "object";
            }

            if (arr.Children.Count == 1 && arr.Children[0] is ParseableCustomField singleLeaf)
                return TypeMapper.GetCSharpTypeName(singleLeaf.ValueType, singleLeaf.EnumType);

            return arr.TypeName;
        }

        private string GetDictionaryValueTypeName(ParseableDictionaryField dict)
        {
            if (dict.Children.Count == 1 && dict.Children[0] is ParseableCustomField singleLeaf)
                return TypeMapper.GetCSharpTypeName(singleLeaf.ValueType, singleLeaf.EnumType);

            return dict.TypeName;
        }

        private static bool HasStructuralChildren(ParseableNode node)
        {
            if (node.Children.Count == 1 && node.Children[0] is ParseableCustomField)
                return false;
            return node.Children.Count > 0;
        }

        private void WriteDatabaseClass(CodeWriter w, string graphName, ParseableNode root)
        {
            var dbClassName = $"{graphName}Database";

            switch (root)
            {
                case ParseableDictionaryRoot dict:
                {
                    var entryClass = dict.TypeName;
                    var keyType = TypeMapper.GetKeyTypeName(dict.KeyType);
                    w.BeginBlock($"public class {dbClassName} : DictionaryDatabaseAsset<{keyType}, {entryClass}>");
                    w.EndBlock();
                    break;
                }

                case ParseableArrayRoot arr:
                {
                    var entryClass = arr.TypeName;
                    w.BeginBlock($"public class {dbClassName} : ArrayDatabaseAsset<{entryClass}>");
                    w.EndBlock();
                    break;
                }

                case ParseableObjectRoot obj:
                {
                    var entryClass = obj.TypeName;
                    w.BeginBlock($"public class {dbClassName} : ObjectDatabaseAsset<{entryClass}>");
                    w.EndBlock();
                    break;
                }
            }
        }
    }
}
