using System;
using System.Collections.Generic;
using DataGraph.Editor.Domain;
using DataGraph.Runtime;

namespace DataGraph.Editor.CodeGen
{
    /// <summary>
    /// Generates Quantum AssetObject database classes from a ParseableGraph.
    /// Entry classes use FP for float/double, FPVector2/FPVector3 for vectors.
    /// String, Color, and asset references are wrapped in #if QUANTUM_UNITY.
    /// Produces a single file per graph containing entry class(es) and database AssetObject.
    /// </summary>
    internal sealed class QuantumCodeGenerator
    {
        /// <summary>
        /// Generates the complete Quantum database file (entries + database AssetObject).
        /// </summary>
        public Result<string> Generate(ParseableGraph graph)
        {
            if (graph == null)
                return Result<string>.Failure("Graph is null.");

            try
            {
                var w = new CodeWriter();
                WriteHeader(w);
                w.BeginBlock("namespace DataGraph.Data");
                WriteEntryClasses(w, graph.Root);
                w.BlankLine();
                WriteDatabaseClass(w, graph.GraphName, graph.Root);
                w.EndBlock();
                return Result<string>.Success(w.ToString());
            }
            catch (Exception ex)
            {
                return Result<string>.Failure($"Quantum code generation failed: {ex.Message}");
            }
        }

        private static void WriteHeader(CodeWriter w)
        {
            w.Line("// <auto-generated>");
            w.Line("// Generated by DataGraph. Do not modify.");
            w.Line("// </auto-generated>");
            w.BlankLine();
            w.Line("using System;");
            w.Line("using System.Collections.Generic;");
            w.Line("using Photon.Deterministic;");
            w.Line("using Quantum;");
            w.BlankLine();
        }

        // ==================== ENTRY CLASSES ====================

        private void WriteEntryClasses(CodeWriter w, ParseableNode root)
        {
            var typeName = RootTypeResolver.GetTypeName(root);
            var keyInfo = root is ParseableDictionaryRoot dict ? dict : null;
            WriteEntryClass(w, typeName, root.Children, keyInfo);
        }

        private void WriteEntryClass(CodeWriter w, string typeName, IReadOnlyList<ParseableNode> children,
            ParseableDictionaryRoot keyInfo = null)
        {
            var entryName = typeName + "QuantumEntry";

            w.Line("[Serializable]");
            w.BeginBlock($"public class {entryName}");

            if (keyInfo != null)
            {
                var keyType = TypeMapper.GetKeyTypeName(keyInfo.KeyType);
                w.Line($"public {keyType} id;");
            }

            bool hasViewFields = false;

            foreach (var child in children)
            {
                if (IsSimulationSafe(child))
                    WriteSimField(w, child);
                else
                    hasViewFields = true;
            }

            if (hasViewFields)
            {
                w.BlankLine();
                w.Line("#if QUANTUM_UNITY");
                foreach (var child in children)
                {
                    if (!IsSimulationSafe(child))
                        WriteViewField(w, child);
                }
                w.Line("#endif");
            }

            w.EndBlock();

            foreach (var child in children)
                WriteNestedClasses(w, child);
        }

        private void WriteSimField(CodeWriter w, ParseableNode node)
        {
            switch (node)
            {
                case ParseableCustomField custom:
                    w.Line($"public {TypeMapper.GetQuantumSimType(custom.ValueType)} {custom.FieldName};");
                    break;
                case ParseableEnumField enumField:
                    w.Line($"public {enumField.EnumTypeName} {enumField.FieldName};");
                    break;
                case ParseableFlagField flagField:
                    w.Line($"public {flagField.FlagTypeName} {flagField.FieldName};");
                    break;
                case ParseableObjectField obj:
                    w.Line($"public {obj.TypeName}QuantumEntry {obj.FieldName};");
                    break;
                case ParseableArrayField arr:
                    var elementType = GetArrayElementQuantumType(arr, sim: true);
                    w.Line($"public List<{elementType}> {arr.FieldName} = new();");
                    break;
                case ParseableDictionaryField dict:
                    var keyType = TypeMapper.GetKeyTypeName(dict.KeyType);
                    var valueType = GetDictionaryValueQuantumType(dict, sim: true);
                    w.Line($"public List<{keyType}> {dict.FieldName}Keys = new();");
                    w.Line($"public List<{valueType}> {dict.FieldName}Values = new();");
                    break;
            }
        }

        private void WriteViewField(CodeWriter w, ParseableNode node)
        {
            switch (node)
            {
                case ParseableCustomField custom:
                    w.Line($"public {TypeMapper.GetQuantumViewType(custom.ValueType)} {custom.FieldName};");
                    break;
                case ParseableAssetField asset:
                    w.Line($"public UnityEngine.{AssetTypeMapper.GetCSharpTypeName(asset.AssetType)} {asset.FieldName};");
                    break;
                case ParseableArrayField arr:
                    var elementType = GetArrayElementQuantumType(arr, sim: false);
                    w.Line($"public List<{elementType}> {arr.FieldName} = new();");
                    break;
            }
        }

        private void WriteNestedClasses(CodeWriter w, ParseableNode node)
        {
            switch (node)
            {
                case ParseableObjectField obj:
                    w.BlankLine();
                    WriteEntryClass(w, obj.TypeName, obj.Children);
                    break;
                case ParseableArrayField arr when arr.Mode == ArrayMode.Vertical && CodeGenHelpers.HasStructuralChildren(arr):
                    w.BlankLine();
                    WriteEntryClass(w, arr.TypeName, arr.Children);
                    break;
                case ParseableDictionaryField dict when CodeGenHelpers.HasStructuralChildren(dict):
                    w.BlankLine();
                    WriteEntryClass(w, dict.TypeName, dict.Children);
                    break;
            }
        }

        // ==================== DATABASE CLASS ====================

        private void WriteDatabaseClass(CodeWriter w, string graphName, ParseableNode root)
        {
            var dbName = $"{graphName}QuantumDatabase";
            var entryName = RootTypeResolver.GetTypeName(root) + "QuantumEntry";

            w.BeginBlock($"public class {dbName} : AssetObject");
            w.Line($"public List<{entryName}> entries = new();");
            w.BlankLine();
            w.Line("[NonSerialized] private Dictionary<int, int> _lookup;");

            switch (root)
            {
                case ParseableDictionaryRoot dict:
                    WriteDictionaryLookup(w, entryName, dict);
                    break;
                case ParseableArrayRoot:
                    WriteArrayLookup(w, entryName);
                    break;
                case ParseableObjectRoot:
                    WriteObjectLookup(w, entryName);
                    break;
            }

            w.BlankLine();
            WriteLoaded(w);
            w.BlankLine();
            WriteBuildLookup(w, root);

            w.EndBlock();
        }

        private void WriteDictionaryLookup(CodeWriter w, string entryName, ParseableDictionaryRoot root)
        {
            var keyType = TypeMapper.GetKeyTypeName(root.KeyType);
            w.BlankLine();

            if (root.KeyType == KeyType.Int)
            {
                w.BeginBlock($"public {entryName} GetById({keyType} key)");
                w.Line("if (_lookup == null) BuildLookup();");
                w.Line("if (_lookup.TryGetValue(key, out int index))");
                w.Line("    return entries[index];");
                w.Line($"throw new System.Collections.Generic.KeyNotFoundException($\"No {entryName} with id '{{key}}'.\");");
                w.EndBlock();
            }
            else
            {
                w.Line("[NonSerialized] private Dictionary<string, int> _stringLookup;");
                w.BlankLine();
                w.BeginBlock($"public {entryName} GetById({keyType} key)");
                w.Line("if (_stringLookup == null) BuildLookup();");
                w.Line("if (_stringLookup.TryGetValue(key, out int index))");
                w.Line("    return entries[index];");
                w.Line($"throw new System.Collections.Generic.KeyNotFoundException($\"No {entryName} with id '{{key}}'.\");");
                w.EndBlock();
            }
        }

        private void WriteArrayLookup(CodeWriter w, string entryName)
        {
            w.BlankLine();
            w.BeginBlock($"public {entryName} GetByIndex(int index)");
            w.Line("return entries[index];");
            w.EndBlock();
        }

        private void WriteObjectLookup(CodeWriter w, string entryName)
        {
            w.BlankLine();
            w.BeginBlock($"public {entryName} GetObject()");
            w.Line("return entries.Count > 0 ? entries[0] : null;");
            w.EndBlock();
        }

        private static void WriteLoaded(CodeWriter w)
        {
            w.BeginBlock("public override void Loaded(IResourceManager resourceManager, Native.Allocator allocator)");
            w.Line("base.Loaded(resourceManager, allocator);");
            w.Line("BuildLookup();");
            w.EndBlock();
        }

        private void WriteBuildLookup(CodeWriter w, ParseableNode root)
        {
            w.BeginBlock("private void BuildLookup()");

            switch (root)
            {
                case ParseableDictionaryRoot dict when dict.KeyType == KeyType.Int:
                    w.Line("_lookup = new Dictionary<int, int>(entries.Count);");
                    w.Line("for (int i = 0; i < entries.Count; i++)");
                    w.Line("    _lookup[entries[i].id] = i;");
                    break;
                case ParseableDictionaryRoot dict when dict.KeyType == KeyType.String:
                    w.Line("_stringLookup = new Dictionary<string, int>(entries.Count);");
                    w.Line("for (int i = 0; i < entries.Count; i++)");
                    w.Line("    _stringLookup[entries[i].id] = i;");
                    break;
                default:
                    w.Line("// No lookup needed for array/object databases");
                    break;
            }

            w.EndBlock();
        }

        // ==================== TYPE HELPERS ====================

        private static bool IsSimulationSafe(ParseableNode node)
        {
            return node switch
            {
                ParseableCustomField custom => IsSimSafeType(custom.ValueType),
                ParseableEnumField => true,
                ParseableFlagField => true,
                ParseableObjectField => true,
                ParseableArrayField arr => IsArraySimulationSafe(arr),
                ParseableDictionaryField => true,
                ParseableAssetField => false,
                _ => false
            };
        }

        private static bool IsArraySimulationSafe(ParseableArrayField arr)
        {
            if (arr.Children.Count == 0) return true;
            foreach (var child in arr.Children)
            {
                if (!IsSimulationSafe(child)) return false;
            }
            return true;
        }

        private static bool IsSimSafeType(FieldValueType type)
        {
            return type switch
            {
                FieldValueType.Int => true,
                FieldValueType.Float => true,
                FieldValueType.Double => true,
                FieldValueType.Bool => true,
                FieldValueType.Vector2 => true,
                FieldValueType.Vector3 => true,
                FieldValueType.String => false,
                FieldValueType.Color => false,
                _ => false
            };
        }

        private string GetArrayElementQuantumType(ParseableArrayField arr, bool sim)
        {
            if (arr.Mode == ArrayMode.Horizontal)
            {
                if (arr.Children.Count > 0 && arr.Children[0] is ParseableCustomField leaf)
                    return sim ? TypeMapper.GetQuantumSimType(leaf.ValueType) : TypeMapper.GetQuantumViewType(leaf.ValueType);
                return "string";
            }

            if (string.IsNullOrEmpty(arr.TypeName)
                && arr.Children.Count == 1
                && arr.Children[0] is ParseableCustomField singleLeaf)
                return sim ? TypeMapper.GetQuantumSimType(singleLeaf.ValueType) : TypeMapper.GetQuantumViewType(singleLeaf.ValueType);

            return arr.TypeName + "QuantumEntry";
        }

        private string GetDictionaryValueQuantumType(ParseableDictionaryField dict, bool sim)
        {
            if (string.IsNullOrEmpty(dict.TypeName)
                && dict.Children.Count == 1
                && dict.Children[0] is ParseableCustomField singleLeaf)
                return sim ? TypeMapper.GetQuantumSimType(singleLeaf.ValueType) : TypeMapper.GetQuantumViewType(singleLeaf.ValueType);

            return dict.TypeName + "QuantumEntry";
        }

    }
}
