// <auto-generated>
// Generated by DataGraph. Do not modify.
// </auto-generated>

using System;
using System.Collections.Generic;
using Photon.Deterministic;
using Quantum;

namespace DataGraph.Data
{
    [Serializable]
    public class HeroQuantumEntry
    {
        public int id;
        public EAttribute attribute;
        public StatQuantumEntry stat;
        public FAttribute flag;

        #if QUANTUM_UNITY
        public string name;
        #endif
    }

    [Serializable]
    public class StatQuantumEntry
    {
        public int mana;
        public int hp;
    }

    public class HeroGraphQuantumDatabase : AssetObject
    {
        public List<HeroQuantumEntry> entries = new();

        [NonSerialized] private Dictionary<int, int> _lookup;

        public HeroQuantumEntry GetById(int key)
        {
            if (_lookup == null) BuildLookup();
            if (_lookup.TryGetValue(key, out int index))
                return entries[index];
            throw new System.Collections.Generic.KeyNotFoundException($"No HeroQuantumEntry with id '{key}'.");
        }

        public override void Loaded(IResourceManager resourceManager, Native.Allocator allocator)
        {
            base.Loaded(resourceManager, allocator);
            BuildLookup();
        }

        private void BuildLookup()
        {
            _lookup = new Dictionary<int, int>(entries.Count);
            for (int i = 0; i < entries.Count; i++)
                _lookup[entries[i].id] = i;
        }
    }
}
