// <auto-generated>
// Generated by DataGraph. Do not modify.
// </auto-generated>

using System;
using System.Collections.Generic;
using Photon.Deterministic;
using Quantum;

namespace DataGraph.Data
{
    [Serializable]
    public class GameConfigQuantumEntry
    {
        public int maxPlayer;
        public FP tickeRate;
        public bool debug;
    }

    public class GameConfigQuantumDatabase : AssetObject
    {
        public List<GameConfigQuantumEntry> entries = new();

        [NonSerialized] private Dictionary<int, int> _lookup;

        public GameConfigQuantumEntry GetObject()
        {
            return entries.Count > 0 ? entries[0] : null;
        }

        public override void Loaded(IResourceManager resourceManager, Native.Allocator allocator)
        {
            base.Loaded(resourceManager, allocator);
            BuildLookup();
        }

        private void BuildLookup()
        {
            // No lookup needed for array/object databases
        }
    }
}
