// <auto-generated>
// Generated by DataGraph. Do not modify.
// </auto-generated>

namespace DataGraph.Data
{
    public enum EAttribute
    {
        None = 0,
        Agility = 1,
        Strenght = 2,
        Inteligence = 3,
        Universal = 4
    }
}
