using System.Collections.Generic;

namespace DataGraph.Editor.Public
{
    /// <summary>
    /// Input context provided to an IOutputSerializer containing
    /// all data needed to produce output files.
    /// </summary>
    public sealed class SerializationContext
    {
        public SerializationContext(
            object parsedDataTree,
            object parseableGraph,
            string outputBasePath,
            string graphName)
        {
            ParsedDataTree = parsedDataTree;
            ParseableGraph = parseableGraph;
            OutputBasePath = outputBasePath;
            GraphName = graphName;
        }

        /// <summary>
        /// The parsed data tree to serialize. Type is object to avoid
        /// exposing internal ParsedDataTree in the public assembly.
        /// Concrete serializers cast to the expected internal type.
        /// </summary>
        public object ParsedDataTree { get; }

        /// <summary>
        /// The graph definition used for code generation. Type is object
        /// for the same reason as ParsedDataTree.
        /// </summary>
        public object ParseableGraph { get; }

        /// <summary>
        /// Base directory path where output files should be written.
        /// </summary>
        public string OutputBasePath { get; }

        /// <summary>
        /// Name of the source graph, used for file naming.
        /// </summary>
        public string GraphName { get; }
    }

    /// <summary>
    /// Output produced by an IOutputSerializer, listing
    /// all files that were generated.
    /// </summary>
    public sealed class SerializationOutput
    {
        public SerializationOutput(IReadOnlyList<string> generatedFiles)
        {
            GeneratedFiles = generatedFiles;
        }

        /// <summary>
        /// Paths to all files generated by this serialization.
        /// </summary>
        public IReadOnlyList<string> GeneratedFiles { get; }
    }
}
