// <auto-generated>
// Generated by DataGraph. Do not modify.
// </auto-generated>

using System;
using System.Collections.Generic;
using Photon.Deterministic;
using Quantum;

namespace DataGraph.Data
{
    [Serializable]
    public class ItemQuantumEntry
    {
        public int id;
        public int dmg;
        public FP speed;
        public bool isRare;
        public FPVector3 spawnPont;
        public FPVector2 pos;
        public DamageQuantumEntry damage;

        #if QUANTUM_UNITY
        public UnityEngine.Color tint;
        #endif
    }

    [Serializable]
    public class DamageQuantumEntry
    {
        public int score;

        #if QUANTUM_UNITY
        public List<string> tags = new();
        #endif
    }

    public class TestAllQuantumDatabase : AssetObject
    {
        public List<ItemQuantumEntry> entries = new();

        [NonSerialized] private Dictionary<int, int> _lookup;

        public ItemQuantumEntry GetById(int key)
        {
            if (_lookup == null) BuildLookup();
            if (_lookup.TryGetValue(key, out int index))
                return entries[index];
            throw new System.Collections.Generic.KeyNotFoundException($"No ItemQuantumEntry with id '{key}'.");
        }

        public override void Loaded(IResourceManager resourceManager, Native.Allocator allocator)
        {
            base.Loaded(resourceManager, allocator);
            BuildLookup();
        }

        private void BuildLookup()
        {
            _lookup = new Dictionary<int, int>(entries.Count);
            for (int i = 0; i < entries.Count; i++)
                _lookup[entries[i].id] = i;
        }
    }
}
