// <auto-generated>
// Generated by DataGraph. Do not modify.
// </auto-generated>

namespace DataGraph.Data
{
    [System.Flags]
    public enum FAttribute
    {
        None = 0,
        Agility = 1,
        Strenght = 2,
        Inteligence = 4,
        Universal = 8
    }
}
