// <auto-generated>
// Generated by DataGraph. Do not modify.
// </auto-generated>

using System;
using System.Collections.Generic;
using Photon.Deterministic;
using Quantum;

namespace DataGraph.Data
{
    [Serializable]
    public class GearQuantumEntry
    {
        public int id;
        public List<SkillQuantumEntry> skills = new();

        #if QUANTUM_UNITY
        public string name;
        #endif
    }

    [Serializable]
    public class SkillQuantumEntry
    {
        public int skillId;
        public List<LevelQuantumEntry> levels = new();
    }

    [Serializable]
    public class LevelQuantumEntry
    {
        public int req;
        public int power;
    }

    public class GearQuantumDatabase : AssetObject
    {
        public List<GearQuantumEntry> entries = new();

        [NonSerialized] private Dictionary<int, int> _lookup;

        public GearQuantumEntry GetById(int key)
        {
            if (_lookup == null) BuildLookup();
            if (_lookup.TryGetValue(key, out int index))
                return entries[index];
            throw new System.Collections.Generic.KeyNotFoundException($"No GearQuantumEntry with id '{key}'.");
        }

        public override void Loaded(IResourceManager resourceManager, Native.Allocator allocator)
        {
            base.Loaded(resourceManager, allocator);
            BuildLookup();
        }

        private void BuildLookup()
        {
            _lookup = new Dictionary<int, int>(entries.Count);
            for (int i = 0; i < entries.Count; i++)
                _lookup[entries[i].id] = i;
        }
    }
}
